name: Maven Dependency Check
on:
  pull_request:
    branches:
      - main
jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2
      - name: Run Dependency-Check
        run: mvn org.owasp:dependency-check-maven:check -Dformat=JSON -DoutputDirectory=dependency-check-report
      - name: Parse Dependency Check Report
        id: parse-report
        run: |
          # Check if a report was generated
          if [ ! -f dependency-check-report/dependency-check-report.json ]; then
            echo "No dependency check report found, failing build."
            exit 1
          fi
          
          # Count vulnerabilities in the report using jq
          VULNERABILITIES=$(jq '.dependencies | map(select(.vulnerabilities)) | length' dependency-check-report/dependency-check-report.json)
          echo "Total vulnerabilities found: $VULNERABILITIES"
          
          # Fail the build if any vulnerabilities are found
          if [ "$VULNERABILITIES" -gt 0 ]; then
            echo "Vulnerabilities found, failing the build."
            exit 1
          fi
      - name: Clean up Dependency Check Report
        run: rm -rf dependency-check-report