name: Run Dependabot Core

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  dependabot-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7 # Dependabot-core requires Ruby 2.7

      # Run Dependabot-core in Docker
      - name: Run Dependabot Core
        run: |
          docker run --rm \
              -v "$(pwd):/home/dependabot/dependabot-script" \
              -w "/home/dependabot/dependabot-script" \
              dependabot/dependabot-core \
              bundle exec ruby ./update_script.rb
